### PR TITLE
Possible fix for #381

### PR DESCRIPTION
**Pull request by SiriosDev**
Possible fix for #381
I modified the code so that it precisely controls the expected tag (and relative tests)

### CODE REVIEW

**Comment by MichelFR** [comment]
Thanks a lot for the contribution did not new about the difference.

Have you tested the changes you did yourself? Did you encounter any side effects?

If everything is fine I’m gonna merge this and create a new release, I currently don’t have the time to test

**Comment by MichelFR** [comment]
No it seems to be fine from code side, thanks a lot for the contribution.

**Comment by SiriosDev** [comment]
> No it seems to be fine from code side, thanks a lot for the contribution.

do you find the other changes I wrote useful or do I avoid continuing them?

these 👇

> I'm also working on preventing the service from restarting when it doesn't find a container and/or an image by having it handle the error (maybe removing the corresponding entry), on post-update operations (so that it restarts the container if it's found turned on and vice versa), and on a way to exclude some containers from the check (so that local ones created with dockerfile or other are ignored).

**Comment by MichelFR** [comment]
I think it would make sense implementing all of that.
Especially the functionality to ignore specific defined containers.

**Comment by SiriosDev** [comment]
Nice, Then I give it priority 👌

**Pull request merged**
